server:
  port: 8082
  servlet:
    context-path: /

security:

  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8094/sso-server/oauth/token
      userAuthorizationUri: http://localhost:8094/sso-server/oauth/authorize
    resource:
      userInfoUri: http://localhost:8094/sso-server/user/me
spring:
  thymeleaf:
    cache: false